### ISSUE TITLE
Verify if expression plots with minimaps work on the CBU machines

### ISSUE THREAD

**Issue by caiw** [kymata-atlas/kymata-core#409]
They don't work on Windows (#408) but we should verify if they work on on the CBU machines as a workaround.

**Comment by neukym** [comment]
@young-x-skyee, can you check this? you might have done so already but can you do it again? Can you use the `main` branch and `invoke_plotting.py` to confirm, as we did on your local PC.

**Comment by neukym** [comment]
sure I will now. 👍

**Comment by neukym** [comment]
As expected, it doesn't work. Let me see if I can fix this though.

```bash
/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/plot/plot.py:296: UserWarning: Plotting on the fsaverage brain. Ensure that hexel numbers match those of the fsaverage brain.
  warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/invokers/invoker_run_nkg_plotting.py", line 166, in <module>
    main()
  File "/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/invokers/invoker_run_nkg_plotting.py", line 24, in main
    fig = expression_plot(
          ^^^^^^^^^^^^^^^^
  File "/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/plot/plot.py", line 691, in expression_plot
    _plot_minimap_hexel(
  File "/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/plot/plot.py", line 319, in _plot_minimap_hexel
    lh_brain = stc.plot(hemi="lh", **plot_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/at03/.cache/pypoetry/virtualenvs/kymata-9z-PYDBX-py3.11/lib/python3.11/site-packages/mne/source_estimate.py", line 789, in plot
    brain = plot_source_estimates(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-187>", line 12, in plot_source_estimates
  File "/home/at03/.cache/pypoetry/virtualenvs/kymata-9z-PYDBX-py3.11/lib/python3.11/site-packages/mne/viz/_3d.py", line 2406, in plot_source_estimates
    backend = _get_3d_backend()
              ^^^^^^^^^^^^^^^^^
  File "/home/at03/.cache/pypoetry/virtualenvs/kymata-9z-PYDBX-py3.11/lib/python3.11/site-packages/mne/viz/backends/renderer.py", line 181, in _get_3d_backend
    raise RuntimeError(
RuntimeError: Could not load any valid 3D backend
pyvistaqt: No Qt bindings could be found
notebook: No module named 'ipyevents'

 install pyvistaqt, using pip or conda:
'pip install pyvistaqt'
'conda install -c conda-forge pyvistaqt'

 or install ipywidgets, if using a notebook backend
'pip install ipywidgets'
'conda install -c conda-forge ipywidgets'
```

**Comment by neukym** [comment]
output of mne.sys_info

```bash
Platform             Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.36
Python               3.11.7 (main, Jan 11 2024, 10:43:21) [GCC 12.2.0]
Executable           /home/at03/.cache/pypoetry/virtualenvs/kymata-9z-PYDBX-py3.11/bin/python
CPU                   (32 cores)
Memory               251.4 GB

Core
- mne               1.8.0 (latest release)
-  numpy             1.26.4 (OpenBLAS 0.3.23.dev with 32 threads)
- scipy             1.14.1
- matplotlib        3.9.2 (backend=agg)

Numerical (optional)
- sklearn           1.5.2
- numba             0.58.1
- nibabel           5.3.2
- pandas            2.2.3
- h5io              0.1.10
- h5py              3.12.1
- unavailable       nilearn, dipy, openmeeg, cupy

Visualization (optional)
- pyvista           0.44.1 (OpenGL unavailable)
- pyvistaqt         0.11.1
- ipywidgets        8.1.5
- unavailable       vtk, qtpy, ipympl, pyqtgraph, mne-qt-browser, trame_client, trame_server, trame_vtk, trame_vuetify

Ecosystem (optional)
- unavailable       mne-bids, mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline, neo, eeglabio, edfio, mffpy, pybv
None
```

**Comment by neukym** [comment]
Anthony has got it working if we use Conda - so this can work as a temporary solution. He and I are working on other solutions now - keeping this open while we sort this.

**Comment by neukym** [comment]
PR #413 fixes this - but we are not going to merge it in, as it includes a number of hacks that are specific to the CBU nodes. Instead, we will keep this PR as an interim measure while we wait for the new cluster to come online, and then remove it when no longer needed.
